/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Memon enterprises
 */
public class CustomerInterface extends javax.swing.JFrame {
    
    String account_number = "";

    
    public CustomerInterface(String accNo) {
        initComponents();
        
        account_number = accNo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEcoPulseLimited = new javax.swing.JLabel();
        btnCustomerInterfaceLogout = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnBillingRates = new javax.swing.JButton();
        btnMeterReadings = new javax.swing.JButton();
        btnBills = new javax.swing.JButton();
        btnPaymentStatus = new javax.swing.JButton();
        btnComplaint = new javax.swing.JButton();
        Sep1 = new javax.swing.JSeparator();
        Sep2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Interface");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblEcoPulseLimited.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEcoPulseLimited.setForeground(new java.awt.Color(102, 102, 102));
        lblEcoPulseLimited.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcoPulseLimited.setText("EcoPulse Private Limited");

        btnCustomerInterfaceLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnCustomerInterfaceLogout.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnCustomerInterfaceLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerInterfaceLogout.setText("Logout");
        btnCustomerInterfaceLogout.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnCustomerInterfaceLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerInterfaceLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomerInterfaceLogoutMouseExited(evt);
            }
        });
        btnCustomerInterfaceLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerInterfaceLogoutActionPerformed(evt);
            }
        });

        btnInfo.setBackground(new java.awt.Color(102, 102, 102));
        btnInfo.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnInfo.setText("Info");
        btnInfo.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInfoMouseExited(evt);
            }
        });
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnBillingRates.setBackground(new java.awt.Color(102, 102, 102));
        btnBillingRates.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnBillingRates.setForeground(new java.awt.Color(255, 255, 255));
        btnBillingRates.setText("Billing Rates");
        btnBillingRates.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnBillingRates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBillingRatesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBillingRatesMouseExited(evt);
            }
        });
        btnBillingRates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingRatesActionPerformed(evt);
            }
        });

        btnMeterReadings.setBackground(new java.awt.Color(102, 102, 102));
        btnMeterReadings.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnMeterReadings.setForeground(new java.awt.Color(255, 255, 255));
        btnMeterReadings.setText("Meter Readings");
        btnMeterReadings.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnMeterReadings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMeterReadingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMeterReadingsMouseExited(evt);
            }
        });
        btnMeterReadings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeterReadingsActionPerformed(evt);
            }
        });

        btnBills.setBackground(new java.awt.Color(102, 102, 102));
        btnBills.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnBills.setForeground(new java.awt.Color(255, 255, 255));
        btnBills.setText("Bills");
        btnBills.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBillsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBillsMouseExited(evt);
            }
        });
        btnBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillsActionPerformed(evt);
            }
        });

        btnPaymentStatus.setBackground(new java.awt.Color(102, 102, 102));
        btnPaymentStatus.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnPaymentStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnPaymentStatus.setText("Payment Status");
        btnPaymentStatus.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnPaymentStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaymentStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaymentStatusMouseExited(evt);
            }
        });
        btnPaymentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentStatusActionPerformed(evt);
            }
        });

        btnComplaint.setBackground(new java.awt.Color(102, 102, 102));
        btnComplaint.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnComplaint.setForeground(new java.awt.Color(255, 255, 255));
        btnComplaint.setText("Complaint");
        btnComplaint.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnComplaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComplaintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComplaintMouseExited(evt);
            }
        });
        btnComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnPaymentStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addComponent(btnComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBillingRates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMeterReadings, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnBills, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCustomerInterfaceLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(Sep1)
            .addComponent(Sep2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBillingRates, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMeterReadings, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBills, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Sep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCustomerInterfaceLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerInterfaceLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerInterfaceLogoutMouseEntered
        // TODO add your handling code here:
        btnCustomerInterfaceLogout.setBackground(new Color(255, 255, 255));
        btnCustomerInterfaceLogout.setForeground(new Color(102, 102, 102));
        btnCustomerInterfaceLogout.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnCustomerInterfaceLogout.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnCustomerInterfaceLogoutMouseEntered

    private void btnCustomerInterfaceLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerInterfaceLogoutMouseExited
        // TODO add your handling code here:
        btnCustomerInterfaceLogout.setBackground(new Color(102, 102, 102));
        btnCustomerInterfaceLogout.setForeground(new Color(255, 255, 255));
        btnCustomerInterfaceLogout.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnCustomerInterfaceLogout.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnCustomerInterfaceLogoutMouseExited

    private void btnInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseEntered
        // TODO add your handling code here:
        btnInfo.setBackground(new Color(255, 255, 255));
        btnInfo.setForeground(new Color(102, 102, 102));
        btnInfo.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnInfo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnInfoMouseEntered

    private void btnInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseExited
        // TODO add your handling code here:
        btnInfo.setBackground(new Color(102, 102, 102));
        btnInfo.setForeground(new Color(255, 255, 255));
        btnInfo.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnInfo.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnInfoMouseExited

    private void btnBillingRatesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillingRatesMouseEntered
        // TODO add your handling code here:
        btnBillingRates.setBackground(new Color(255, 255, 255));
        btnBillingRates.setForeground(new Color(102, 102, 102));
        btnBillingRates.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnBillingRates.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnBillingRatesMouseEntered

    private void btnBillingRatesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillingRatesMouseExited
        // TODO add your handling code here:
        btnBillingRates.setBackground(new Color(102, 102, 102));
        btnBillingRates.setForeground(new Color(255, 255, 255));
        btnBillingRates.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnBillingRates.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnBillingRatesMouseExited

    private void btnMeterReadingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeterReadingsMouseEntered
        // TODO add your handling code here:
        btnMeterReadings.setBackground(new Color(255, 255, 255));
        btnMeterReadings.setForeground(new Color(102, 102, 102));
        btnMeterReadings.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnMeterReadings.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnMeterReadingsMouseEntered

    private void btnMeterReadingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeterReadingsMouseExited
        // TODO add your handling code here:
        btnMeterReadings.setBackground(new Color(102, 102, 102));
        btnMeterReadings.setForeground(new Color(255, 255, 255));
        btnMeterReadings.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnMeterReadings.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnMeterReadingsMouseExited

    private void btnBillsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillsMouseEntered
        // TODO add your handling code here:
        btnBills.setBackground(new Color(255, 255, 255));
        btnBills.setForeground(new Color(102, 102, 102));
        btnBills.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnBills.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnBillsMouseEntered

    private void btnBillsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillsMouseExited
        // TODO add your handling code here:
        btnBills.setBackground(new Color(102, 102, 102));
        btnBills.setForeground(new Color(255, 255, 255));
        btnBills.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnBills.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnBillsMouseExited

    private void btnPaymentStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentStatusMouseEntered
        // TODO add your handling code here:
        btnPaymentStatus.setBackground(new Color(255, 255, 255));
        btnPaymentStatus.setForeground(new Color(102, 102, 102));
        btnPaymentStatus.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnPaymentStatus.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPaymentStatusMouseEntered

    private void btnPaymentStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentStatusMouseExited
        // TODO add your handling code here:
        btnPaymentStatus.setBackground(new Color(102, 102, 102));
        btnPaymentStatus.setForeground(new Color(255, 255, 255));
        btnPaymentStatus.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnPaymentStatus.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPaymentStatusMouseExited

    private void btnComplaintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComplaintMouseEntered
        // TODO add your handling code here:
        btnComplaint.setBackground(new Color(255, 255, 255));
        btnComplaint.setForeground(new Color(102, 102, 102));
        btnComplaint.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnComplaint.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnComplaintMouseEntered

    private void btnComplaintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComplaintMouseExited
        // TODO add your handling code here:
        btnComplaint.setBackground(new Color(102, 102, 102));
        btnComplaint.setForeground(new Color(255, 255, 255));
        btnComplaint.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnComplaint.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnComplaintMouseExited

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        
        // Customer Interface Info Created
        new CustomerInterfaceInfo(account_number).setVisible(true);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnBillingRatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingRatesActionPerformed
        // TODO add your handling code here:
        
        // Customer Interface Billing Rates Created
        new CustomerInterfaceBillingRates().setVisible(true);
    }//GEN-LAST:event_btnBillingRatesActionPerformed

    private void btnMeterReadingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeterReadingsActionPerformed
        // TODO add your handling code here:
        
        // Customer interface Meter Readings Created
        new CustomerInterfaceMeterReadings().setVisible(true);
    }//GEN-LAST:event_btnMeterReadingsActionPerformed

    private void btnBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillsActionPerformed
        // TODO add your handling code here:
        
        // Customer Interface Bill Created
        new CustomerInterfaceBills(account_number).setVisible(true);
    }//GEN-LAST:event_btnBillsActionPerformed

    private void btnCustomerInterfaceLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerInterfaceLogoutActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnCustomerInterfaceLogoutActionPerformed

    private void btnPaymentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentStatusActionPerformed
        // TODO add your handling code here:
        
        // Customer Interface Payment Status Created
        new CustomerInterfacePaymentStatus(account_number).setVisible(true);
    }//GEN-LAST:event_btnPaymentStatusActionPerformed

    private void btnComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplaintActionPerformed
        // TODO add your handling code here:
        
        // Customer Interface Complaint Created
        new CustomerInterfaceComplaint(account_number).setVisible(true);
    }//GEN-LAST:event_btnComplaintActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Sep1;
    private javax.swing.JSeparator Sep2;
    private javax.swing.JButton btnBillingRates;
    private javax.swing.JButton btnBills;
    private javax.swing.JButton btnComplaint;
    private javax.swing.JButton btnCustomerInterfaceLogout;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnMeterReadings;
    private javax.swing.JButton btnPaymentStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEcoPulseLimited;
    // End of variables declaration//GEN-END:variables
}
