/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Memon enterprises
 */
public class CustomerLoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    
    
       
    public CustomerLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAccNo = new javax.swing.JTextField();
        lblAccNo = new javax.swing.JLabel();
        lblEcoPulseLimited = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        btnCustomerLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Login Page");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        txtAccNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAccNo.setForeground(new java.awt.Color(102, 102, 102));
        txtAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccNoActionPerformed(evt);
            }
        });

        lblAccNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAccNo.setForeground(new java.awt.Color(102, 102, 102));
        lblAccNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAccNo.setText("Account Number");

        lblEcoPulseLimited.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEcoPulseLimited.setForeground(new java.awt.Color(102, 102, 102));
        lblEcoPulseLimited.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcoPulseLimited.setText("EcoPulse Private Limited");

        lblLogin.setBackground(new java.awt.Color(102, 102, 102));
        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(102, 102, 102));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Login");
        lblLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));

        btnCustomerLogin.setBackground(new java.awt.Color(102, 102, 102));
        btnCustomerLogin.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnCustomerLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerLogin.setText("Login");
        btnCustomerLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnCustomerLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomerLoginMouseExited(evt);
            }
        });
        btnCustomerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCustomerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnCustomerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       
    private void txtAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccNoActionPerformed

    private void btnCustomerLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerLoginMouseEntered
        // TODO add your handling code here:
        btnCustomerLogin.setBackground(new Color(255, 255, 255));
        btnCustomerLogin.setForeground(new Color(102, 102, 102));
        btnCustomerLogin.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnCustomerLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnCustomerLoginMouseEntered

    private void btnCustomerLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerLoginMouseExited
        // TODO add your handling code here:
        btnCustomerLogin.setBackground(new Color(102, 102, 102));
        btnCustomerLogin.setForeground(new Color(255, 255, 255));
        btnCustomerLogin.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnCustomerLogin.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnCustomerLoginMouseExited

    private void btnCustomerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerLoginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnCustomerLoginActionPerformed

    
    // JDBC Connection
        
    // URL, USERNAME, PASSWORD
    String url = "jdbc:mysql://localhost:3306/electricitybillingsystem";
    String username = "root";
    String password = "noemak";
    
    // Login Validation For Customer
    public void login(){
        // Establishing Connection
        try {
            Connection con = DriverManager.getConnection(url, username, password);
            System.out.println("Connection Established Successfully!");
            String query = "SELECT * FROM Customers;";
            PreparedStatement prepStm = con.prepareStatement(query);
            ResultSet res = prepStm.executeQuery();
            
            
            // Text Field
            int text = Integer.parseInt(txtAccNo.getText());
            boolean flag = false;
            
            while(res.next()){
                int acc_no = res.getInt("account_number");
                
                if( text == acc_no ){
                    flag = true;
                    // Creating Operator Interface
                    new CustomerInterface(txtAccNo.getText()).setVisible(true);
                    // Disposing This Window
                    dispose();
                }
            }
            
            if(!flag)
                JOptionPane.showMessageDialog(null, "Enter Correct Account Number!");
            
            res.close();
            prepStm.close();
            con.close();
            
        } catch (SQLException excp) {
            System.out.println(excp.getMessage());
        }
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblEcoPulseLimited;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JTextField txtAccNo;
    // End of variables declaration//GEN-END:variables
}
