/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;


import java.awt.Color;
import java.awt.Cursor;
import javax.swing.border.MatteBorder;


/**
 *
 * @author Noem Ahmed Khan
 */
public class Main extends javax.swing.JFrame {
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOperator = new javax.swing.JButton();
        lblEcoPulseLimited = new javax.swing.JLabel();
        btnCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        btnOperator.setBackground(new java.awt.Color(102, 102, 102));
        btnOperator.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        btnOperator.setForeground(new java.awt.Color(255, 255, 255));
        btnOperator.setText("Operator");
        btnOperator.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnOperator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOperatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOperatorMouseExited(evt);
            }
        });
        btnOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperatorActionPerformed(evt);
            }
        });

        lblEcoPulseLimited.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEcoPulseLimited.setForeground(new java.awt.Color(102, 102, 102));
        lblEcoPulseLimited.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcoPulseLimited.setText("EcoPulse Private Limited");

        btnCustomer.setBackground(new java.awt.Color(102, 102, 102));
        btnCustomer.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setText("Customer");
        btnCustomer.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomerMouseExited(evt);
            }
        });
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOperatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOperatorMouseEntered
        // TODO add your handling code here:
        btnOperator.setBackground(new Color(255, 255, 255));
        btnOperator.setForeground(new Color(102, 102, 102));
        btnOperator.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnOperator.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnOperatorMouseEntered

    private void btnOperatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOperatorMouseExited
        // TODO add your handling code here:
        btnOperator.setBackground(new Color(102, 102, 102));
        btnOperator.setForeground(new Color(255, 255, 255));
        btnOperator.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnOperator.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnOperatorMouseExited

    private void btnOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperatorActionPerformed
        // TODO add your handling code here:

        // Operator Login Page Created
        OperatorLoginPage oprLogin = new OperatorLoginPage();
        oprLogin.setVisible(true);

        // Disposing This Page
        dispose();
    }//GEN-LAST:event_btnOperatorActionPerformed

    private void btnCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseEntered
        // TODO add your handling code here:
        btnCustomer.setBackground(new Color(255, 255, 255));
        btnCustomer.setForeground(new Color(102, 102, 102));
        btnCustomer.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnCustomer.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnCustomerMouseEntered

    private void btnCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseExited
        // TODO add your handling code here:
        btnCustomer.setBackground(new Color(102, 102, 102));
        btnCustomer.setForeground(new Color(255, 255, 255));
        btnCustomer.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnCustomer.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnCustomerMouseExited

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:

        // Customer Login Page Created
        CustomerLoginPage custLogin = new CustomerLoginPage();
        custLogin.setVisible(true);

        // Disposing This Page
        dispose();
    }//GEN-LAST:event_btnCustomerActionPerformed

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
        
        
        // Loading Drivers
        try {
            Class.forName("com.mysql.jdbc.Drivers");
            System.out.println("Drivers Loaded Successfully!");
        } catch (ClassNotFoundException excp) {
            System.out.println(excp.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnOperator;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEcoPulseLimited;
    // End of variables declaration//GEN-END:variables
}
