/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Memon enterprises
 */
public class OperatorInterface extends javax.swing.JFrame {
    
    /**
     * Creates new form AdminWindow
     */

    
    public OperatorInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblEcoPulseLimited = new javax.swing.JLabel();
        btnOperatorInterfaceLogout = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnBillingRates = new javax.swing.JButton();
        btnMeters = new javax.swing.JButton();
        btnMeterReadings = new javax.swing.JButton();
        btnBills = new javax.swing.JButton();
        btnCharges = new javax.swing.JButton();
        btnPaymentStatus = new javax.swing.JButton();
        btnComplaint = new javax.swing.JButton();
        Sep1 = new javax.swing.JSeparator();
        Sep2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operator Interface");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblEcoPulseLimited.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEcoPulseLimited.setForeground(new java.awt.Color(102, 102, 102));
        lblEcoPulseLimited.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcoPulseLimited.setText("EcoPulse Private Limited");

        btnOperatorInterfaceLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnOperatorInterfaceLogout.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnOperatorInterfaceLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnOperatorInterfaceLogout.setText("Logout");
        btnOperatorInterfaceLogout.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnOperatorInterfaceLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOperatorInterfaceLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOperatorInterfaceLogoutMouseExited(evt);
            }
        });
        btnOperatorInterfaceLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperatorInterfaceLogoutActionPerformed(evt);
            }
        });

        btnCustomers.setBackground(new java.awt.Color(102, 102, 102));
        btnCustomers.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomers.setText("Customers");
        btnCustomers.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomersMouseExited(evt);
            }
        });
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });

        btnBillingRates.setBackground(new java.awt.Color(102, 102, 102));
        btnBillingRates.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnBillingRates.setForeground(new java.awt.Color(255, 255, 255));
        btnBillingRates.setText("Billing Rates");
        btnBillingRates.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnBillingRates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBillingRatesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBillingRatesMouseExited(evt);
            }
        });
        btnBillingRates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingRatesActionPerformed(evt);
            }
        });

        btnMeters.setBackground(new java.awt.Color(102, 102, 102));
        btnMeters.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnMeters.setForeground(new java.awt.Color(255, 255, 255));
        btnMeters.setText("Meters");
        btnMeters.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnMeters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMetersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMetersMouseExited(evt);
            }
        });
        btnMeters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetersActionPerformed(evt);
            }
        });

        btnMeterReadings.setBackground(new java.awt.Color(102, 102, 102));
        btnMeterReadings.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnMeterReadings.setForeground(new java.awt.Color(255, 255, 255));
        btnMeterReadings.setText("Meter Readings");
        btnMeterReadings.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnMeterReadings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMeterReadingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMeterReadingsMouseExited(evt);
            }
        });
        btnMeterReadings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeterReadingsActionPerformed(evt);
            }
        });

        btnBills.setBackground(new java.awt.Color(102, 102, 102));
        btnBills.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnBills.setForeground(new java.awt.Color(255, 255, 255));
        btnBills.setText("Bills");
        btnBills.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBillsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBillsMouseExited(evt);
            }
        });
        btnBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillsActionPerformed(evt);
            }
        });

        btnCharges.setBackground(new java.awt.Color(102, 102, 102));
        btnCharges.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnCharges.setForeground(new java.awt.Color(255, 255, 255));
        btnCharges.setText("Charges");
        btnCharges.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnCharges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChargesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChargesMouseExited(evt);
            }
        });
        btnCharges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargesActionPerformed(evt);
            }
        });

        btnPaymentStatus.setBackground(new java.awt.Color(102, 102, 102));
        btnPaymentStatus.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnPaymentStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnPaymentStatus.setText("Payment Status");
        btnPaymentStatus.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnPaymentStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaymentStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaymentStatusMouseExited(evt);
            }
        });
        btnPaymentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentStatusActionPerformed(evt);
            }
        });

        btnComplaint.setBackground(new java.awt.Color(102, 102, 102));
        btnComplaint.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnComplaint.setForeground(new java.awt.Color(255, 255, 255));
        btnComplaint.setText("Complaint");
        btnComplaint.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnComplaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComplaintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComplaintMouseExited(evt);
            }
        });
        btnComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCharges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBillingRates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPaymentStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMeterReadings, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(btnComplaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMeters, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOperatorInterfaceLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(Sep1)
            .addComponent(Sep2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBillingRates, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMeterReadings, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMeters, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBills, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnOperatorInterfaceLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOperatorInterfaceLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOperatorInterfaceLogoutMouseEntered
        // TODO add your handling code here:
        btnOperatorInterfaceLogout.setBackground(new Color(255, 255, 255));
        btnOperatorInterfaceLogout.setForeground(new Color(102, 102, 102));
        btnOperatorInterfaceLogout.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnOperatorInterfaceLogout.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnOperatorInterfaceLogoutMouseEntered

    private void btnOperatorInterfaceLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOperatorInterfaceLogoutMouseExited
        // TODO add your handling code here:
        btnOperatorInterfaceLogout.setBackground(new Color(102, 102, 102));
        btnOperatorInterfaceLogout.setForeground(new Color(255, 255, 255));
        btnOperatorInterfaceLogout.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnOperatorInterfaceLogout.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnOperatorInterfaceLogoutMouseExited

    private void btnCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseEntered
        // TODO add your handling code here:
        btnCustomers.setBackground(new Color(255, 255, 255));
        btnCustomers.setForeground(new Color(102, 102, 102));
        btnCustomers.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnCustomers.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnCustomersMouseEntered

    private void btnCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseExited
        // TODO add your handling code here:
        btnCustomers.setBackground(new Color(102, 102, 102));
        btnCustomers.setForeground(new Color(255, 255, 255));
        btnCustomers.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnCustomers.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnCustomersMouseExited

    private void btnBillingRatesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillingRatesMouseEntered
        // TODO add your handling code here:
        btnBillingRates.setBackground(new Color(255, 255, 255));
        btnBillingRates.setForeground(new Color(102, 102, 102));
        btnBillingRates.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnBillingRates.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnBillingRatesMouseEntered

    private void btnBillingRatesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillingRatesMouseExited
        // TODO add your handling code here:
        btnBillingRates.setBackground(new Color(102, 102, 102));
        btnBillingRates.setForeground(new Color(255, 255, 255));
        btnBillingRates.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnBillingRates.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnBillingRatesMouseExited

    private void btnMetersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMetersMouseEntered
        // TODO add your handling code here:
        btnMeters.setBackground(new Color(255, 255, 255));
        btnMeters.setForeground(new Color(102, 102, 102));
        btnMeters.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnMeters.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnMetersMouseEntered

    private void btnMetersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMetersMouseExited
        // TODO add your handling code here:
        btnMeters.setBackground(new Color(102, 102, 102));
        btnMeters.setForeground(new Color(255, 255, 255));
        btnMeters.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnMeters.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnMetersMouseExited

    private void btnMeterReadingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeterReadingsMouseEntered
        // TODO add your handling code here:
        btnMeterReadings.setBackground(new Color(255, 255, 255));
        btnMeterReadings.setForeground(new Color(102, 102, 102));
        btnMeterReadings.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnMeterReadings.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnMeterReadingsMouseEntered

    private void btnMeterReadingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeterReadingsMouseExited
        // TODO add your handling code here:
        btnMeterReadings.setBackground(new Color(102, 102, 102));
        btnMeterReadings.setForeground(new Color(255, 255, 255));
        btnMeterReadings.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnMeterReadings.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnMeterReadingsMouseExited

    private void btnBillsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillsMouseEntered
        // TODO add your handling code here:
        btnBills.setBackground(new Color(255, 255, 255));
        btnBills.setForeground(new Color(102, 102, 102));
        btnBills.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnBills.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnBillsMouseEntered

    private void btnBillsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillsMouseExited
        // TODO add your handling code here:
        btnBills.setBackground(new Color(102, 102, 102));
        btnBills.setForeground(new Color(255, 255, 255));
        btnBills.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnBills.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnBillsMouseExited

    private void btnChargesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChargesMouseEntered
        // TODO add your handling code here:
        btnCharges.setBackground(new Color(255, 255, 255));
        btnCharges.setForeground(new Color(102, 102, 102));
        btnCharges.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnCharges.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnChargesMouseEntered

    private void btnChargesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChargesMouseExited
        // TODO add your handling code here:
        btnCharges.setBackground(new Color(102, 102, 102));
        btnCharges.setForeground(new Color(255, 255, 255));
        btnCharges.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnCharges.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnChargesMouseExited

    private void btnPaymentStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentStatusMouseEntered
        // TODO add your handling code here:
        btnPaymentStatus.setBackground(new Color(255, 255, 255));
        btnPaymentStatus.setForeground(new Color(102, 102, 102));
        btnPaymentStatus.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnPaymentStatus.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPaymentStatusMouseEntered

    private void btnPaymentStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentStatusMouseExited
        // TODO add your handling code here:
        btnPaymentStatus.setBackground(new Color(102, 102, 102));
        btnPaymentStatus.setForeground(new Color(255, 255, 255));
        btnPaymentStatus.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnPaymentStatus.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPaymentStatusMouseExited

    private void btnComplaintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComplaintMouseEntered
        // TODO add your handling code here:
        btnComplaint.setBackground(new Color(255, 255, 255));
        btnComplaint.setForeground(new Color(102, 102, 102));
        btnComplaint.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnComplaint.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnComplaintMouseEntered

    private void btnComplaintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComplaintMouseExited
        // TODO add your handling code here:
        btnComplaint.setBackground(new Color(102, 102, 102));
        btnComplaint.setForeground(new Color(255, 255, 255));
        btnComplaint.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnComplaint.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnComplaintMouseExited

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        // TODO add your handling code here:
        
       // Operator Interface Customer List Created
       OperatorInterfaceCustomersList oprIntCustList = new OperatorInterfaceCustomersList();
       oprIntCustList.setVisible(true);
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnBillingRatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingRatesActionPerformed
        // TODO add your handling code here:
        
        // Operator Interface Billing Rates Created
        OperatorInterfaceBillingRates oprIntBillRates = new OperatorInterfaceBillingRates();
        oprIntBillRates.setVisible(true);
    }//GEN-LAST:event_btnBillingRatesActionPerformed

    private void btnMeterReadingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeterReadingsActionPerformed
        // TODO add your handling code here:
        
        // Operator Interface Meter Readings Created
        OperatorInterfaceMeterReadings oprIntMeterReadings = new OperatorInterfaceMeterReadings();
        oprIntMeterReadings.setVisible(true);
    }//GEN-LAST:event_btnMeterReadingsActionPerformed

    private void btnMetersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetersActionPerformed
        // TODO add your handling code here:
        
        // Operator Interface Meters List Created
        OperatorInterfaceMetersList oprIntMeterList = new OperatorInterfaceMetersList();
        oprIntMeterList.setVisible(true);
    }//GEN-LAST:event_btnMetersActionPerformed

    private void btnChargesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargesActionPerformed
        // TODO add your handling code here:
        
        // Operator Interface Charges Created
        OperatorInterfaceCharges oprIntCharges = new OperatorInterfaceCharges();
        oprIntCharges.setVisible(true);
    }//GEN-LAST:event_btnChargesActionPerformed

    private void btnPaymentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentStatusActionPerformed
        // TODO add your handling code here:
        
        // Operator Interface Payment Status Created
        OperatorInterfacePaymentStatus oprIntPayStatus = new OperatorInterfacePaymentStatus();
        oprIntPayStatus.setVisible(true);
    }//GEN-LAST:event_btnPaymentStatusActionPerformed

    private void btnComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplaintActionPerformed
        // TODO add your handling code here:
        
        // Operator Interface Complaint Created
        OperatorInterfaceComplaint oprIntComplaint = new OperatorInterfaceComplaint();
        oprIntComplaint.setVisible(true);
    }//GEN-LAST:event_btnComplaintActionPerformed

    private void btnBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillsActionPerformed
        // TODO add your handling code here:
        
        // Operator Interface Bill Created
        OperatorInterfaceBills oprIntBill = new OperatorInterfaceBills();
        oprIntBill.setVisible(true);
    }//GEN-LAST:event_btnBillsActionPerformed

    private void btnOperatorInterfaceLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperatorInterfaceLogoutActionPerformed
        // TODO add your handling code here:
        
        // Open Main Frame
        new Main().setVisible(true);
        
        // Dispose This Frame
        dispose();
    }//GEN-LAST:event_btnOperatorInterfaceLogoutActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Sep1;
    private javax.swing.JSeparator Sep2;
    private javax.swing.JButton btnBillingRates;
    private javax.swing.JButton btnBills;
    private javax.swing.JButton btnCharges;
    private javax.swing.JButton btnComplaint;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnMeterReadings;
    private javax.swing.JButton btnMeters;
    private javax.swing.JButton btnOperatorInterfaceLogout;
    private javax.swing.JButton btnPaymentStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEcoPulseLimited;
    // End of variables declaration//GEN-END:variables
}
