/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noem Ahmed Khan
 */
public class OperatorInterfaceComplaint extends javax.swing.JFrame {
    
    // Creating Default Table Model To Insert & Delete Data
    DefaultTableModel model;
    
    public OperatorInterfaceComplaint() {
        initComponents();
        
        // To Center the table header text
        ((DefaultTableCellRenderer) OperatorInterfaceComplaint.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(javax.swing.JLabel.CENTER);
        
        // Set column auto resizable
        OperatorInterfaceComplaint.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        // Default Table Model Initialization
        model = (DefaultTableModel) OperatorInterfaceComplaint.getModel();
        
         // JDBC Connection
        
         // URL, USERNAME, PASSWORD
        String url = "jdbc:mysql://localhost:3306/electricitybillingsystem";
        String username = "root";
        String password = "noemak";
    
        // Establishing Connection
        try {
            Connection con = DriverManager.getConnection(url, username, password);
            System.out.println("Connection Established Successfully!");
            String query = "SELECT * FROM complaint;";
            PreparedStatement prepStm = con.prepareStatement(query);
            ResultSet res = prepStm.executeQuery();
           
            while(res.next()){
                String complaint_id = res.getString("complaint_ID");
                String accNo = res.getString("account_number");
                String description = res.getString("description");
                String report_date = res.getString("report_date");
                String status = res.getString("status");
                
                String data[] = {complaint_id, accNo, description, report_date, status};
                model.addRow(data);
            }
            
            res.close();
            prepStm.close();
            con.close();
            
            } catch (SQLException excp) {
                System.out.println(excp.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sep1 = new javax.swing.JPanel();
        lblEcoPulseLimited = new javax.swing.JLabel();
        btnReview = new javax.swing.JButton();
        btnInProcess = new javax.swing.JButton();
        BillsScrollPanel = new javax.swing.JScrollPane();
        OperatorInterfaceComplaint = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        Sep3 = new javax.swing.JSeparator();
        btnReceived = new javax.swing.JButton();
        btnResolved = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Complaint");

        Sep1.setBackground(new java.awt.Color(0, 153, 153));

        lblEcoPulseLimited.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEcoPulseLimited.setForeground(new java.awt.Color(102, 102, 102));
        lblEcoPulseLimited.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcoPulseLimited.setText("EcoPulse Private Limited");

        btnReview.setBackground(new java.awt.Color(102, 102, 102));
        btnReview.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnReview.setForeground(new java.awt.Color(255, 255, 255));
        btnReview.setText("Review");
        btnReview.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnReview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReviewMouseExited(evt);
            }
        });
        btnReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewActionPerformed(evt);
            }
        });

        btnInProcess.setBackground(new java.awt.Color(102, 102, 102));
        btnInProcess.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnInProcess.setForeground(new java.awt.Color(255, 255, 255));
        btnInProcess.setText("In Process");
        btnInProcess.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnInProcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInProcessMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInProcessMouseExited(evt);
            }
        });
        btnInProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInProcessActionPerformed(evt);
            }
        });

        OperatorInterfaceComplaint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OperatorInterfaceComplaint.setForeground(new java.awt.Color(102, 102, 102));
        OperatorInterfaceComplaint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Complaint ID", "Account No", "Description", "Report Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OperatorInterfaceComplaint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OperatorInterfaceComplaint.setFocusable(false);
        OperatorInterfaceComplaint.setGridColor(new java.awt.Color(204, 204, 204));
        OperatorInterfaceComplaint.setName("Complaint"); // NOI18N
        OperatorInterfaceComplaint.setRowHeight(30);
        OperatorInterfaceComplaint.setSelectionBackground(new java.awt.Color(102, 102, 102));
        OperatorInterfaceComplaint.setSelectionForeground(new java.awt.Color(255, 255, 255));
        OperatorInterfaceComplaint.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        OperatorInterfaceComplaint.getTableHeader().setReorderingAllowed(false);
        BillsScrollPanel.setViewportView(OperatorInterfaceComplaint);

        btnReceived.setBackground(new java.awt.Color(102, 102, 102));
        btnReceived.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnReceived.setForeground(new java.awt.Color(255, 255, 255));
        btnReceived.setText("Received");
        btnReceived.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnReceived.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReceivedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReceivedMouseExited(evt);
            }
        });
        btnReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceivedActionPerformed(evt);
            }
        });

        btnResolved.setBackground(new java.awt.Color(102, 102, 102));
        btnResolved.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnResolved.setForeground(new java.awt.Color(255, 255, 255));
        btnResolved.setText("Resolved");
        btnResolved.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnResolved.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResolvedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResolvedMouseExited(evt);
            }
        });
        btnResolved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolvedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Sep1Layout = new javax.swing.GroupLayout(Sep1);
        Sep1.setLayout(Sep1Layout);
        Sep1Layout.setHorizontalGroup(
            Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(Sep1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnReview, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnInProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnResolved, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Sep1Layout.createSequentialGroup()
                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sep1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sep1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BillsScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE))
                    .addGroup(Sep1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Sep3)))
                .addContainerGap())
        );
        Sep1Layout.setVerticalGroup(
            Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sep1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BillsScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sep3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReview, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResolved, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReviewMouseEntered
        // TODO add your handling code here:
        btnReview.setBackground(new Color(255, 255, 255));
        btnReview.setForeground(new Color(102, 102, 102));
        btnReview.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnReview.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnReviewMouseEntered

    private void btnReviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReviewMouseExited
        // TODO add your handling code here:
        btnReview.setBackground(new Color(102, 102, 102));
        btnReview.setForeground(new Color(255, 255, 255));
        btnReview.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnReview.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnReviewMouseExited

    private void btnReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewActionPerformed
        // TODO add your handling code here:

        int selectedRow = OperatorInterfaceComplaint.getSelectedRow();

        if (selectedRow != -1) {
             // JDBC Connection
        
             // URL, USERNAME, PASSWORD
            String url = "jdbc:mysql://localhost:3306/electricitybillingsystem";
            String username = "root";
            String password = "noemak";
    
            // Establishing Connection
            try {
                Connection con = DriverManager.getConnection(url, username, password);
                System.out.println("Connection Established Successfully!");
                String complaint_id = OperatorInterfaceComplaint.getValueAt(selectedRow, 0).toString();
                String query = "UPDATE complaint SET status = 'Review' WHERE complaint_ID = " + complaint_id + ";";
                PreparedStatement prepStm = con.prepareStatement(query);
                int rowsAffected = prepStm.executeUpdate();
           
                prepStm.close();
                con.close();
            
            } catch (SQLException excp) {
                System.out.println(excp.getMessage());
            }
        }
        else{
             // Show message if no row is selected
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }//GEN-LAST:event_btnReviewActionPerformed

    private void btnInProcessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInProcessMouseEntered
        // TODO add your handling code here:
        btnInProcess.setBackground(new Color(255, 255, 255));
        btnInProcess.setForeground(new Color(102, 102, 102));
        btnInProcess.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnInProcess.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnInProcessMouseEntered

    private void btnInProcessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInProcessMouseExited
        // TODO add your handling code here:
        btnInProcess.setBackground(new Color(102, 102, 102));
        btnInProcess.setForeground(new Color(255, 255, 255));
        btnInProcess.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnInProcess.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnInProcessMouseExited

    private void btnInProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInProcessActionPerformed
        // TODO add your handling code here:
   
        int selectedRow = OperatorInterfaceComplaint.getSelectedRow();

        if (selectedRow != -1) {
             // JDBC Connection
        
             // URL, USERNAME, PASSWORD
            String url = "jdbc:mysql://localhost:3306/electricitybillingsystem";
            String username = "root";
            String password = "noemak";
    
            // Establishing Connection
            try {
                Connection con = DriverManager.getConnection(url, username, password);
                System.out.println("Connection Established Successfully!");
                String complaint_id = OperatorInterfaceComplaint.getValueAt(selectedRow, 0).toString();
                String query = "UPDATE complaint SET status = 'In Process' WHERE complaint_ID = " + complaint_id + ";";
                PreparedStatement prepStm = con.prepareStatement(query);
                int rowsAffected = prepStm.executeUpdate();
           
                prepStm.close();
                con.close();
            
            } catch (SQLException excp) {
                System.out.println(excp.getMessage());
            }
        }
        else{
             // Show message if no row is selected
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }//GEN-LAST:event_btnInProcessActionPerformed

    private void btnReceivedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReceivedMouseEntered
        // TODO add your handling code here:
        btnReceived.setBackground(new Color(255, 255, 255));
        btnReceived.setForeground(new Color(102, 102, 102));
        btnReceived.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnReceived.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnReceivedMouseEntered

    private void btnReceivedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReceivedMouseExited
        // TODO add your handling code here:
        btnReceived.setBackground(new Color(102, 102, 102));
        btnReceived.setForeground(new Color(255, 255, 255));
        btnReceived.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnReceived.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnReceivedMouseExited

    private void btnReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceivedActionPerformed
        // TODO add your handling code here:
        int selectedRow = OperatorInterfaceComplaint.getSelectedRow();

        if (selectedRow != -1) {
             // JDBC Connection
        
             // URL, USERNAME, PASSWORD
            String url = "jdbc:mysql://localhost:3306/electricitybillingsystem";
            String username = "root";
            String password = "noemak";
    
            // Establishing Connection
            try {
                Connection con = DriverManager.getConnection(url, username, password);
                System.out.println("Connection Established Successfully!");
                String complaint_id = OperatorInterfaceComplaint.getValueAt(selectedRow, 0).toString();
                String query = "UPDATE complaint SET status = 'Received' WHERE complaint_ID = " + complaint_id + ";";
                PreparedStatement prepStm = con.prepareStatement(query);
                int rowsAffected = prepStm.executeUpdate();
           
                prepStm.close();
                con.close();
            
            } catch (SQLException excp) {
                System.out.println(excp.getMessage());
            }
        }
        else{
             // Show message if no row is selected
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }//GEN-LAST:event_btnReceivedActionPerformed

    private void btnResolvedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResolvedMouseEntered
        // TODO add your handling code here:
        btnResolved.setBackground(new Color(255, 255, 255));
        btnResolved.setForeground(new Color(102, 102, 102));
        btnResolved.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnResolved.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnResolvedMouseEntered

    private void btnResolvedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResolvedMouseExited
        // TODO add your handling code here:
        btnResolved.setBackground(new Color(102, 102, 102));
        btnResolved.setForeground(new Color(255, 255, 255));
        btnResolved.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnResolved.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnResolvedMouseExited

    private void btnResolvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolvedActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = OperatorInterfaceComplaint.getSelectedRow();

        if (selectedRow != -1) {
             // JDBC Connection
        
             // URL, USERNAME, PASSWORD
            String url = "jdbc:mysql://localhost:3306/electricitybillingsystem";
            String username = "root";
            String password = "noemak";
    
            // Establishing Connection
            try {
                Connection con = DriverManager.getConnection(url, username, password);
                System.out.println("Connection Established Successfully!");
                String complaint_id = OperatorInterfaceComplaint.getValueAt(selectedRow, 0).toString();
                String query = "UPDATE complaint SET status = 'Resolved' WHERE complaint_ID = " + complaint_id + ";";
                PreparedStatement prepStm = con.prepareStatement(query);
                int rowsAffected = prepStm.executeUpdate();
           
                prepStm.close();
                con.close();
            
            } catch (SQLException excp) {
                System.out.println(excp.getMessage());
            }
        }
        else{
             // Show message if no row is selected
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }//GEN-LAST:event_btnResolvedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfaceComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfaceComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfaceComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfaceComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane BillsScrollPanel;
    private javax.swing.JTable OperatorInterfaceComplaint;
    private javax.swing.JPanel Sep1;
    private javax.swing.JSeparator Sep3;
    private javax.swing.JButton btnInProcess;
    private javax.swing.JButton btnReceived;
    private javax.swing.JButton btnResolved;
    private javax.swing.JButton btnReview;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEcoPulseLimited;
    // End of variables declaration//GEN-END:variables
}
