/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noem Ahmed Khan
 */
public class OperatorInterfaceBills extends javax.swing.JFrame {

    // Creating Default Table Model To Insert & Delete Data
    DefaultTableModel model;
    
    public OperatorInterfaceBills() {
        initComponents();
        
        // To Center the table header text
        ((DefaultTableCellRenderer) OperatorInterfaceBills.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(javax.swing.JLabel.CENTER);
        
        // Default Table Model Initialization
        model = (DefaultTableModel) OperatorInterfaceBills.getModel();
        
        // Set column auto resizable
        OperatorInterfaceBills.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
         // JDBC Connection
        
         // URL, USERNAME, PASSWORD
        String url = "jdbc:mysql://localhost:3306/electricitybillingsystem";
        String username = "root";
        String password = "noemak";
    
        // Establishing Connection
        try {
            Connection con = DriverManager.getConnection(url, username, password);
            System.out.println("Connection Established Successfully!");
            String query = "SELECT * FROM bills;";
            PreparedStatement prepStm = con.prepareStatement(query);
            ResultSet res = prepStm.executeQuery();
           
            while(res.next()){
                String bill_id = res.getString("bill_ID");
                String accNo = res.getString("account_number");
                String meter_reading_ID = res.getString("meter_reading_ID");
                String issue_date = res.getString("issue_date");
                String due_date = res.getString("due_date");
                String month = res.getString("month");
                String year = res.getString("year");
                String amount = res.getString("amount");
                
                String data[] = {bill_id, accNo, meter_reading_ID, issue_date, due_date, month, year, amount};
                model.addRow(data);
            }
            
            prepStm.close();
            con.close();
            
            } catch (SQLException excp) {
                System.out.println(excp.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sep1 = new javax.swing.JPanel();
        lblEcoPulseLimited = new javax.swing.JLabel();
        btnAddBill = new javax.swing.JButton();
        BillsScrollPanel = new javax.swing.JScrollPane();
        OperatorInterfaceBills = new javax.swing.JTable();
        lblBillID = new javax.swing.JLabel();
        txtBillID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Sep2 = new javax.swing.JSeparator();
        Sep3 = new javax.swing.JSeparator();
        lblAccNo = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        lblMeterReadingID = new javax.swing.JLabel();
        txtMeterReadingID = new javax.swing.JTextField();
        lblIssueDate = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        txtDueDate = new javax.swing.JTextField();
        lblMonth = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bills");

        Sep1.setBackground(new java.awt.Color(0, 153, 153));

        lblEcoPulseLimited.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEcoPulseLimited.setForeground(new java.awt.Color(102, 102, 102));
        lblEcoPulseLimited.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcoPulseLimited.setText("EcoPulse Private Limited");

        btnAddBill.setBackground(new java.awt.Color(102, 102, 102));
        btnAddBill.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnAddBill.setForeground(new java.awt.Color(255, 255, 255));
        btnAddBill.setText("Add Bill");
        btnAddBill.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnAddBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddBillMouseExited(evt);
            }
        });
        btnAddBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillActionPerformed(evt);
            }
        });

        OperatorInterfaceBills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OperatorInterfaceBills.setForeground(new java.awt.Color(102, 102, 102));
        OperatorInterfaceBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Account No", "Meter Reading ID", "Issue Date", "Due Date", "Month", "Year", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OperatorInterfaceBills.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OperatorInterfaceBills.setFocusable(false);
        OperatorInterfaceBills.setGridColor(new java.awt.Color(204, 204, 204));
        OperatorInterfaceBills.setName("Bills"); // NOI18N
        OperatorInterfaceBills.setRowHeight(30);
        OperatorInterfaceBills.setSelectionBackground(new java.awt.Color(102, 102, 102));
        OperatorInterfaceBills.setSelectionForeground(new java.awt.Color(255, 255, 255));
        OperatorInterfaceBills.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        OperatorInterfaceBills.getTableHeader().setReorderingAllowed(false);
        BillsScrollPanel.setViewportView(OperatorInterfaceBills);

        lblBillID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBillID.setForeground(new java.awt.Color(102, 102, 102));
        lblBillID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBillID.setText("Bill ID");

        txtBillID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBillID.setForeground(new java.awt.Color(102, 102, 102));
        txtBillID.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));

        lblAccNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAccNo.setForeground(new java.awt.Color(102, 102, 102));
        lblAccNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAccNo.setText("Account Number");

        txtAccNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAccNo.setForeground(new java.awt.Color(102, 102, 102));
        txtAccNo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));

        lblMeterReadingID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMeterReadingID.setForeground(new java.awt.Color(102, 102, 102));
        lblMeterReadingID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMeterReadingID.setText("Meter Reading ID");

        txtMeterReadingID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMeterReadingID.setForeground(new java.awt.Color(102, 102, 102));
        txtMeterReadingID.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));

        lblIssueDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIssueDate.setForeground(new java.awt.Color(102, 102, 102));
        lblIssueDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIssueDate.setText("Issue Date");

        lblDueDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDueDate.setForeground(new java.awt.Color(102, 102, 102));
        lblDueDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDueDate.setText("Due Date");

        txtIssueDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIssueDate.setForeground(new java.awt.Color(102, 102, 102));
        txtIssueDate.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));

        txtDueDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDueDate.setForeground(new java.awt.Color(102, 102, 102));
        txtDueDate.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));

        lblMonth.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMonth.setForeground(new java.awt.Color(102, 102, 102));
        lblMonth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMonth.setText("Month");

        lblYear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblYear.setForeground(new java.awt.Color(102, 102, 102));
        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblYear.setText("Year");

        txtMonth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMonth.setForeground(new java.awt.Color(102, 102, 102));
        txtMonth.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));

        txtYear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtYear.setForeground(new java.awt.Color(102, 102, 102));
        txtYear.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout Sep1Layout = new javax.swing.GroupLayout(Sep1);
        Sep1.setLayout(Sep1Layout);
        Sep1Layout.setHorizontalGroup(
            Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sep1Layout.createSequentialGroup()
                .addGap(794, 794, 794)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
            .addComponent(Sep2)
            .addGroup(Sep1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sep3)
                    .addGroup(Sep1Layout.createSequentialGroup()
                        .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(Sep1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BillsScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Sep1Layout.createSequentialGroup()
                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sep1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBillID)
                            .addComponent(lblBillID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMonth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMonth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Sep1Layout.createSequentialGroup()
                                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAccNo, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(txtAccNo)
                                    .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMeterReadingID, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtMeterReadingID))
                                .addGap(18, 18, 18)
                                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblIssueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtIssueDate))
                                .addGap(18, 18, 18)
                                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtDueDate)))
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Sep1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sep1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddBill, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        Sep1Layout.setVerticalGroup(
            Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sep1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BillsScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBillID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeterReadingID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBillID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMeterReadingID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(Sep3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddBill, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBillMouseEntered
        // TODO add your handling code here:
        btnAddBill.setBackground(new Color(255, 255, 255));
        btnAddBill.setForeground(new Color(102, 102, 102));
        btnAddBill.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnAddBill.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnAddBillMouseEntered

    private void btnAddBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBillMouseExited
        // TODO add your handling code here:
        btnAddBill.setBackground(new Color(102, 102, 102));
        btnAddBill.setForeground(new Color(255, 255, 255));
        btnAddBill.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnAddBill.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnAddBillMouseExited

    private void btnAddBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillActionPerformed
        // TODO add your handling code here:
        String billID, accNo, meterReadingID, issueDate, dueDate, month, year, amount;
        billID = txtBillID.getText();
        accNo = txtAccNo.getText();
        meterReadingID = txtMeterReadingID.getText();
        issueDate = txtIssueDate.getText();
        dueDate = txtDueDate.getText();
        month = txtMonth.getText();
        year = txtYear.getText();
        amount = "";
        
        // Setting fields empty
        txtBillID.setText("");
        txtAccNo.setText("");
        txtMeterReadingID.setText("");
        txtIssueDate.setText("");
        txtDueDate.setText("");
        txtMonth.setText("");
        txtYear.setText("");
        
        // Adding values to the database
        // JDBC Connection
        
        // URL, USERNAME, PASSWORD
        String url = "jdbc:mysql://localhost:3306/electricitybillingsystem";
        String username = "root";
        String password = "noemak";
    
        // Establishing Connection
        try {
            Connection con = DriverManager.getConnection(url, username, password);
            System.out.println("Connection Established Successfully!");
            String query = "SELECT consumed_units, rate_tier FROM meter_readings WHERE meter_reading_ID = " + meterReadingID + ";";
            PreparedStatement prepStm = con.prepareStatement(query);
            ResultSet res = prepStm.executeQuery();
            double consumed_units = 0.0;
            String rateTier = "";
            
            while(res.next()){
                    consumed_units = Double.parseDouble(res.getString("consumed_units"));
                    rateTier = res.getString("rate_tier");
            }
            
            String query2 = "SELECT cost_per_unit FROM Billing_Rates WHERE rate_tier = " + rateTier + ";";
            PreparedStatement prepStm2 = con.prepareStatement(query2);
            ResultSet res2 = prepStm2.executeQuery();
            double cost_per_unit = 0.0;
            
            while(res2.next())
                cost_per_unit = Double.parseDouble(res2.getString("cost_per_unit"));
            
            // Calculating Amount
            amount = String.valueOf(consumed_units * cost_per_unit);
              
            // Insering values to the database
            String query3 = "INSERT INTO bills(bill_ID, account_number, meter_reading_ID, issue_date, due_date, month, year, amount) VALUES (?, ?, ?, ?, ?, ?, ?, ?);";
            PreparedStatement prepStm3 = con.prepareStatement(query3);
            prepStm3.setString(1, billID);
            prepStm3.setString(2, accNo);
            prepStm3.setString(3, meterReadingID);
            prepStm3.setString(4, issueDate);
            prepStm3.setString(5, dueDate);
            prepStm3.setString(6, month);
            prepStm3.setString(7, year);
            prepStm3.setString(8, amount);
            prepStm3.executeUpdate();
            
            res.close();
            res2.close();
            prepStm.close();
            prepStm2.close();
            prepStm3.close();
            con.close();
            
        } catch (SQLException excp) {
            System.out.println(excp.getMessage());
        }
        
        
        String[] data = {billID, accNo, meterReadingID, issueDate, dueDate, month, year, amount};

        // Adding values into the table
        model.addRow(data);
    }//GEN-LAST:event_btnAddBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfaceBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfaceBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfaceBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfaceBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane BillsScrollPanel;
    private javax.swing.JTable OperatorInterfaceBills;
    private javax.swing.JPanel Sep1;
    private javax.swing.JSeparator Sep2;
    private javax.swing.JSeparator Sep3;
    private javax.swing.JButton btnAddBill;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblBillID;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblEcoPulseLimited;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblMeterReadingID;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtBillID;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtMeterReadingID;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
