/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricitybillingsystem;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noem Ahmed Khan
 */
public class OperatorInterfacePaymentStatus extends javax.swing.JFrame {

    // Creating Default Table Model To Insert & Delete Data
    DefaultTableModel model;
    
    public OperatorInterfacePaymentStatus() {
        initComponents();
        
        // To Center the table header text
        ((DefaultTableCellRenderer) OperatorInterfacePaymentStatus.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(javax.swing.JLabel.CENTER);
        
        // Default Table Model Initialization
        model = (DefaultTableModel) OperatorInterfacePaymentStatus.getModel();
        
        // Set column auto resizable
        OperatorInterfacePaymentStatus.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
         // JDBC Connection
        
         // URL, USERNAME, PASSWORD
        String url = "jdbc:mysql://localhost:3306/electricitybillingsystem";
        String username = "root";
        String password = "noemak";
    
        // Establishing Connection
        try {
            Connection con = DriverManager.getConnection(url, username, password);
            System.out.println("Connection Established Successfully!");
            String query = "SELECT * FROM payment_status;";
            PreparedStatement prepStm = con.prepareStatement(query);
            ResultSet res = prepStm.executeQuery();
           
            while(res.next()){
                String bill_id = res.getString("bill_ID");
                String charge_id = res.getString("charge_ID");
                String amount = res.getString("amount");
                String payment_status = res.getString("payment_status");
                
                String data[] = {bill_id, charge_id, amount, payment_status};
                model.addRow(data);
            }
            
            res.close();
            prepStm.close();
            con.close();
            
            } catch (SQLException excp) {
                System.out.println(excp.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sep1 = new javax.swing.JPanel();
        lblEcoPulseLimited = new javax.swing.JLabel();
        PaymentStatusScrollPanel = new javax.swing.JScrollPane();
        OperatorInterfacePaymentStatus = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnMarkPaid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment Status");

        Sep1.setBackground(new java.awt.Color(0, 153, 153));

        lblEcoPulseLimited.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEcoPulseLimited.setForeground(new java.awt.Color(102, 102, 102));
        lblEcoPulseLimited.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcoPulseLimited.setText("EcoPulse Private Limited");

        OperatorInterfacePaymentStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OperatorInterfacePaymentStatus.setForeground(new java.awt.Color(102, 102, 102));
        OperatorInterfacePaymentStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Charge ID", "Amount", "Payment Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OperatorInterfacePaymentStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OperatorInterfacePaymentStatus.setFocusable(false);
        OperatorInterfacePaymentStatus.setGridColor(new java.awt.Color(204, 204, 204));
        OperatorInterfacePaymentStatus.setName("Payment Status"); // NOI18N
        OperatorInterfacePaymentStatus.setRowHeight(30);
        OperatorInterfacePaymentStatus.setSelectionBackground(new java.awt.Color(102, 102, 102));
        OperatorInterfacePaymentStatus.setSelectionForeground(new java.awt.Color(255, 255, 255));
        OperatorInterfacePaymentStatus.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        OperatorInterfacePaymentStatus.getTableHeader().setReorderingAllowed(false);
        PaymentStatusScrollPanel.setViewportView(OperatorInterfacePaymentStatus);

        btnMarkPaid.setBackground(new java.awt.Color(102, 102, 102));
        btnMarkPaid.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnMarkPaid.setForeground(new java.awt.Color(255, 255, 255));
        btnMarkPaid.setText("Mark Paid");
        btnMarkPaid.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        btnMarkPaid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMarkPaidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMarkPaidMouseExited(evt);
            }
        });
        btnMarkPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkPaidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Sep1Layout = new javax.swing.GroupLayout(Sep1);
        Sep1.setLayout(Sep1Layout);
        Sep1Layout.setHorizontalGroup(
            Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(Sep1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(PaymentStatusScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sep1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMarkPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        Sep1Layout.setVerticalGroup(
            Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sep1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblEcoPulseLimited, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PaymentStatusScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnMarkPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarkPaidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarkPaidMouseEntered
        // TODO add your handling code here:
        btnMarkPaid.setBackground(new Color(255, 255, 255));
        btnMarkPaid.setForeground(new Color(102, 102, 102));
        btnMarkPaid.setBorder(new MatteBorder(4, 4, 4, 4, new Color(102, 102, 102)));
        btnMarkPaid.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnMarkPaidMouseEntered

    private void btnMarkPaidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarkPaidMouseExited
        // TODO add your handling code here:
        btnMarkPaid.setBackground(new Color(102, 102, 102));
        btnMarkPaid.setForeground(new Color(255, 255, 255));
        btnMarkPaid.setBorder(new MatteBorder(4, 4, 4, 4, new Color(255, 255, 255)));
        btnMarkPaid.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnMarkPaidMouseExited

    private void btnMarkPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkPaidActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = OperatorInterfacePaymentStatus.getSelectedRow();

        if (selectedRow != -1) {
            String bill_id = String.valueOf( model.getValueAt(selectedRow, 0) );
            
            // JDBC Connection

            // URL, USERNAME, PASSWORD
            String url = "jdbc:mysql://localhost:3306/electricitybillingsystem";
            String username = "root";
            String password = "noemak";

            // Establishing Connection
            try {
                Connection con = DriverManager.getConnection(url, username, password);
                System.out.println("Connection Established Successfully!");
                String query = "UPDATE payment_status SET payment_status = 'Paid' WHERE bill_ID = " + bill_id + ";";
                PreparedStatement prepStm = con.prepareStatement(query);
                prepStm.executeUpdate();

                prepStm.close();
                con.close();

            } catch (SQLException excp) {
                System.out.println(excp.getMessage());
            }
        }
        else{
            // Show message if no row is selected
            JOptionPane.showMessageDialog(this, "Please select a row.");
        }
    }//GEN-LAST:event_btnMarkPaidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfacePaymentStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfacePaymentStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfacePaymentStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatorInterfacePaymentStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OperatorInterfacePaymentStatus;
    private javax.swing.JScrollPane PaymentStatusScrollPanel;
    private javax.swing.JPanel Sep1;
    private javax.swing.JButton btnMarkPaid;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEcoPulseLimited;
    // End of variables declaration//GEN-END:variables
}
